# Generated by Django 4.2.7 on 2024-02-03 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovery',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 20, 15, 16, 113324, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pioneer',
            name='description',
            field=models.TextField(default='Биография', verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='pioneer',
            name='name',
            field=models.CharField(default='Имя и фамилия', max_length=100, verbose_name='Имя'),
        ),
    ]
