# Generated by Django 4.2.7 on 2024-02-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_discovery_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovery',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
